/**
 * Pronunciations for rap vocabulary the CMU dictionary lacks (or says in a
 * way nobody raps it). Checked before the dictionary.
 */
export const SLANG: Record<string, string> = {
  ay: 'EY1',
  ayy: 'EY1',
  ayo: 'EY1 OW1',
  bae: 'B EY1',
  bih: 'B IH1',
  boi: 'B OY1',
  bruh: 'B R AH1',
  brr: 'B ER1',
  brrr: 'B ER1',
  bussin: 'B AH1 S IH0 N',
  choppa: 'CH AA1 P AH0',
  coulda: 'K UH1 D AH0',
  cuz: 'K AH1 Z',
  da: 'D AH0',
  dat: 'D AE1 T',
  dawg: 'D AO1 G',
  deadass: 'D EH1 D AE2 S',
  draco: 'D R EY1 K OW0',
  dunno: 'D AH0 N OW1',
  finna: 'F IH1 N AH0',
  fo: 'F OW1',
  gangsta: 'G AE1 NG S T AH0',
  gimme: 'G IH1 M IY0',
  grr: 'G ER1',
  guap: 'G W AA1 P',
  gurl: 'G ER1 L',
  highkey: 'HH AY1 K IY2',
  homie: 'HH OW1 M IY0',
  homies: 'HH OW1 M IY0 Z',
  hunnid: 'HH AH1 N IH0 D',
  hunnids: 'HH AH1 N IH0 D Z',
  hustla: 'HH AH1 S L AH0',
  ima: 'AY1 M AH0',
  imma: 'AY1 M AH0',
  kinda: 'K AY1 N D AH0',
  killa: 'K IH1 L AH0',
  lambo: 'L AE1 M B OW0',
  lemme: 'L EH1 M IY0',
  litty: 'L IH1 T IY0',
  lowkey: 'L OW1 K IY2',
  luv: 'L AH1 V',
  mo: 'M OW1',
  mula: 'M UW1 L AH0',
  nah: 'N AA1',
  nuff: 'N AH1 F',
  ol: 'OW1 L',
  opp: 'AA1 P',
  opps: 'AA1 P S',
  outta: 'AW1 T AH0',
  playa: 'P L EY1 AH0',
  rari: 'R AA1 R IY0',
  shawty: 'SH AO1 T IY0',
  sheesh: 'SH IY1 SH',
  shoulda: 'SH UH1 D AH0',
  skrrt: 'S K ER1 T',
  sorta: 'S AO1 R T AH0',
  tha: 'DH AH0',
  tho: 'DH OW1',
  thot: 'TH AA1 T',
  thru: 'TH R UW1',
  tiktok: 'T IH1 K T AA2 K',
  tryna: 'T R AY1 N AH0',
  turnt: 'T ER1 N T',
  woulda: 'W UH1 D AH0',
  ya: 'Y AH0',
  yuh: 'Y AH1',
}
